feat(docs): chat tutorials
ConduitPlatform/Conduit-Website pull request #124
Opened 2022-12-07 15:52 UTC by sdimitris

**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [ ] No

**The PR fulfills these requirements:**

- [ ] It's submitted to the `main` branch
- [ ] When resolving a specific issue, it's referenced in the PR's description  (e.g. `fix #xxx`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature 

**Other information:**

2022-12-07 16:00 UTC, kon14 requested changes

2022-12-07 16:00 UTC, kon14 commented on documentation/versioned_docs/version-v0.15/modules/chat/tutorials/start_chatting.mdx
> +To begin explaining how to create a chat functionality, some assumptions must be made.
reword "how to create a chat functionality"

2022-12-07 16:00 UTC, kon14 commented on documentation/versioned_docs/version-v0.15/modules/chat/tutorials/start_chatting.mdx
> +We'll need a chat room with some users to participate in now that users have been created. We can accomplish this in two ways:
~"Having created some users, we can create a chat room in a couple of ways..." or sth

2022-12-07 16:00 UTC, kon14 commented on documentation/versioned_docs/version-v0.15/modules/chat/tutorials/start_chatting.mdx
> +To begin, a user must be logged in before proceeding with the creation of a room. In the case of using the local authentication strategy,
in case of*

2022-12-07 16:00 UTC, kon14 commented on documentation/versioned_docs/version-v0.15/modules/chat/tutorials/start_chatting.mdx
> +Three individuals will be placed in a room dubbed ***Conduit Users***. It should be clear that in order to build a chat room, the logged-in userId is not necessary
The authenticated user id should not be included....* or sth

2022-12-07 16:00 UTC, kon14 commented on documentation/versioned_docs/version-v0.15/modules/chat/tutorials/start_chatting.mdx
> +If user fits in the room successfully then an appropriate message will be returned to you.
remove line

2022-12-07 16:00 UTC, kon14 commented on documentation/versioned_docs/version-v0.15/modules/chat/tutorials/start_chatting.mdx
> +```json title="Resposne"
Response*

2022-12-07 16:00 UTC, kon14 commented on documentation/versioned_docs/version-v0.15/modules/chat/tutorials/start_chatting.mdx
> +```json title="Resposne"
Response*

2022-12-07 16:00 UTC, kon14 commented on documentation/versioned_docs/version-v0.15/modules/chat/tutorials/start_chatting.mdx
> +```json title="Resposne"
Response

2023-01-10 10:43 UTC, kkopanidis approved these changes

2023-01-10 10:43 UTC, merged